function Contact() {
  return (
    <>
      <section className="py-5 text-center container">
        <div className="row py-lg-5">
          <div className="col-lg-6 col-md-8 mx-auto">
            <h1 className="fw-light">Contact page</h1>
          </div>
        </div>
      </section>

      <div className="album py-5 bg-light">
        <p className="container lead text-muted">
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text...
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
        </p>
        <p className="container lead text-muted">
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text...
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
        </p>
        <p className="container lead text-muted">
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text...
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
        </p>
        <p className="container lead text-muted">
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text...
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
          Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... Contact page text... 
        </p>
      </div>
    </>
  );
}

export default Contact;
